name = "JunctionTrees"
uuid = "b732b382-80b5-46a8-aa9c-7d077ae04823"
authors = ["Martin Roa Villescas <mroavi@gmail.com>"]
version = "0.3.2"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"

[compat]
AbstractTrees = "0.3.4, 0.4"
Combinatorics = "1.0.2"
DataStructures = "0.18.11"
DocStringExtensions = "0.8.6, 0.9"
Graphs = "1.6.0"
MacroTools = "0.5.9"
MetaGraphs = "0.7.1"
julia = "1.7.0"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
